var lang = 'zh';
var interLang_P;
var GetRequest = function(id) {
	var url = location.search; //获取url中"?"符后的字串
	var theRequest = new Object();
	if(url.indexOf("?") != -1) {
		var str = url.substr(1);
		strs = str.split("&");
		for(var i = 0; i < strs.length; i++) {
			theRequest[strs[i].split("=")[0]] = (strs[i].split("=")[1]);
			theRequest[i] = (strs[i].split("=")[1]);
		}
		if(id) {
			return theRequest[id];
		} else {
			return theRequest;
		}
	} else {
		return false;
	}
}
lang = GetRequest('__lg') ? GetRequest('__lg') : GetRequest('lang');
//lang="en";
if(lang=="zh"){
	interLang_P={
		invite_download:'邀请下载',
		invite_mycode:"我的邀请码",
		invite_copy:'复制',
		invite_register_write:'注册时填写',
		invite_download_app:'下载APP',
		invite_copy_success:'复制成功',

		
		invite_peoples:'邀请人数',
		invite_time:'选择时间',
		invite_searchid:'搜索ID',
		invite_bindnums:'绑定人数',
		invite_lasttime:'最后活跃时间',
		invite_earn_money:'快去邀请好友赚取收益',
		invite_starttime:'开始时间',
		invite_endtime:'结束时间',
		invite_reset:'重置条件',
		invite_sure:'确认',
		invite_date:'日期',


		invite_income_detail:'收益详情',
		invite_friendid:'好友ID',
		invite_chargetype:'充值类型',
		invite_paytype:'支付类型',
		invite_income_num:'充值金额',
		invite_charge_amount:'充值金额净额',
		invite_get_rate:'提成比例',
		invite_percent_reward:'提成奖励（邀请币）',
		invite_charge_time:'充值时间',


		invite_allget_detail:'邀请员收益明细',
		invite_income_bills:'收益明细',
		invite_charge_percent:'充值提成',
		invite_from:'来自',
		invite_no_record:'没有找到相关记录',
		invite_reback_gold:'金币充值返还奖励',
		invite_vip_reward:'VIP升级返还奖励',
		invite_svip_reward:'SVIP升级返还奖励',


		invite_friend_reward:'邀请好友返奖励',
		invite_balance:'奖励余额',
		invite_normal_account:'邀请账号正常！',
		invite_error_account:'邀请账号已被冻结，不予提现！',
		invite_get:'领取',
		invite_total_reward:'累计奖励',
		invite_total_nums:'累计邀请人数',
		invite_reward:'邀请奖励',
		invite_charge_reward:'金币充值奖励',
		invite_percent4:'4%分成',
		invite_intro:'说明',
		invite_now_gold:'邀请好友充值，您将立即获得邀请币；',
		invite_gold_money:'邀请币数量=好友充值金额',
		invite_income_preview:'收益预演',
		invite_case_one:'案例1：您邀请好友充值1万美元，您将立即获得邀请币数量=',
		invite_get_gold400:'您得400邀请币',
		invite_grade_reward:'会员升级奖励：',
		invite_percent8:'8%分成',
		invite_grade_nowget:'邀请好友升级会员，您将立即获得邀请币；',
		invite_nums_grade:'邀请币数量=好友升级会员金额',
		invite_case_two:'案例1：您邀请好友升级会员花费9.99美元，您将立即获得邀请币数量=',
		invite_gold_x:'您得X邀请币。',
		invite_rules:'邀请规则',
		invite_rules_con1:'1.所有用户都可参与邀请计划；',
		invite_rules_con2:'2.您发送自己的邀请码或者分享邀请链接至好友；被邀 请好友注册时，填入邀请码，即可绑定至您名下；',
		invite_rules_con3:'3.被邀请好友充值，您可获得4%邀请币分成；好友升级 会员，您可获得8%邀请币分成；',
		invite_rules_con4:'4.如果您的好友使用苹果和谷歌支付，因苹果商店和谷 歌商店会收取30%手续费，分成会按照实际到账的净额 来计算；',
		invite_rules_con5:'5.邀请币分成将实时到账；',
		invite_rules_con6:'6.如有疑问，请咨询客服',
		invite_go:'去邀请',
		invite_copy_href:'邀请链接复制成功,发送给朋友绑定邀请赚取收益吧',
		invite_more100:'邀请币余额达到100才能申请领取收益',
		invite_fun_now:'该功能即将上线',

	}
	
}else if(lang=="ru"){
	interLang_P={
		invite_download:'Пригласить скачать', 
		invite_mycode:"Мой код приглашения",
		invite_copy:'копия',                    
		invite_register_write:'Заполните при регистрации',
		invite_download_app:'Скачать приложение', 
		invite_copy_success:'Копировать успешно',

		
		invite_peoples:'Количество приглашений',
		invite_time:'период выбора',
		invite_searchid:'ID поиска', 
		invite_bindnums:'Количество связанных людей',
		invite_lasttime:'Время последней активности', 
		invite_earn_money:'Спешите пригласить друзей зарабатывать деньги', 
		invite_starttime:'Время начала',
		invite_endtime:'Время окончания', 
		invite_reset:'Сбросить условие', 
		invite_sure:'подтвердить', 
		invite_date:'Дата', 


		invite_income_detail:'Подробная информация о преимуществах', 
		invite_friendid:'друзья ID', 
		invite_chargetype:'Тип пополнения', 
		invite_paytype:'Типы платежей', 
		invite_income_num:'Сумма пополнения', 
		invite_charge_amount:'Чистая сумма пополнения', 
		invite_get_rate:'Коэффициент комиссии', 
		invite_percent_reward:'Комиссионное вознаграждение (пригласительная монета)', 
		invite_charge_time:'Время перезарядки', 


		invite_allget_detail:'детали о доходах приглашающего', 
		invite_income_bills:'детали о дохода', 
		invite_charge_percent:'Комиссия за пополнение', 
		invite_from:'откуда', 
		invite_no_record:'Соответствующих записей не найдено', 
		invite_reback_gold:'Награды за  пополнение счета золотыми монетами', 
		invite_vip_reward:'Награды за повышение класса VIP', 
		invite_svip_reward:'Награды за повышение класса SVIP', 


		invite_friend_reward:'Пригласите друзей, чтобы получить награды', 
		invite_balance:'Баланс вознаграждения', 
		invite_normal_account:'Инвайт-аккаунт нормальный', 
		invite_error_account:'Учетная запись приглашения была заморожена, и вывод средств невозможен!', 
		invite_get:'получение', 
		invite_total_reward:'Накопительное вознаграждение',  
		invite_total_nums:'Общее количество инвайтов', 
		invite_reward:'Награда за приглашение',  
		invite_charge_reward:'Награды за пополнение баланса золотыми монетами',  
		invite_percent4:'комиссия 4%',  
		invite_intro:'Описание', 
		invite_now_gold:'Пригласите друзей на пополнение баланса и вы сразу получите пригласительные монеты;', 
		invite_gold_money:'Количество пригласительных монет = сумма пополнения баланса друзей.', 
		invite_income_preview:'Предварительный просмотр доходов', 
		invite_case_one:'Случай 1: Вы приглашаете друга пополнить счет на 10 000 долларов США, и сразу получаете количество пригласительных монет =',  
		invite_get_gold400:'Вы получаете 400 пригласительных монет', 
		invite_grade_reward:'Награды за повышение статуса ВИП',  
		invite_percent8:'комиссия 8%',  
		invite_grade_nowget:'Пригласите друзей для обновления членства, вы сразу получите пригласительные монеты;', 
		invite_nums_grade:'Количество пригласительных монет = количество друзей, повышающих членство', 
		invite_case_two:'Случай 1: Если вы пригласите друга для повышения уровня членства, это будет стоить 9,99 долларов США, и вы сразу получите количество пригласительных монет =', 
		invite_gold_x:'Вы получаете X пригласительных монет', 
		invite_rules:'Правила приглашения', 
		invite_rules_con1:'1,Все пользователи могут участвовать в программе приглашения', 
		invite_rules_con2:'2,Вы отправляете свой собственный код приглашения или делитесь ссылкой приглашения с друзьями; когда вас приглашают зарегистрироваться, введите код приглашения, чтобы привязать его к своему имени;', 
		invite_rules_con3:'3,Когда приглашенный друг пополняется, вы можете получить 4% от пригласительной монеты; если ваш друг перейдет на членство, вы можете получить 8% от пригласительной монеты;', 
		invite_rules_con4:'4,Если ваши друзья используют Apple и Google Pay, поскольку Apple Store и Google Store взимают комиссию за обработку в размере 30%, доля будет рассчитываться на основе фактически полученной чистой суммы;', 
		invite_rules_con5:'5. Доля пригласительных монет будет начислена в режиме реального времени.', 
		invite_rules_con6:'6,Если у вас есть вопросы, обратитесь в службу поддержки клиентов.', 
		invite_go:'Приглашать', 
		invite_copy_href:'Ссылка-приглашение успешно скопирована, отправьте ее другу, чтобы привязать приглашение, чтобы заработать деньги', 
		invite_more100:'Только когда баланс пригласительных монет достигнет 100, вы сможете подавать заявку на получение дохода', 
		invite_fun_now:'Эта функция скоро будет запущена', 

	}
	
}else if(lang=="es"){
	interLang_P={
		"invite_fun_now":"Esta función estará en línea pronto",
		"invite_more100":"Para solicitar percibir ganancias, el saldo de monedas de invitación tiene que llegar hasta 100",
		"invite_copy_href":"Éxito de la copia del enlace de invitación",
		"invite_rules_con5":"5. El dividendo de monedas de invitación se recibirá en tiempo real;",
		"invite_rules_con3":"3. Si el amigo invitado recarga, usted podrá obtener un dividendo de monedas de invitación de 4%; si el amigo llega a ser miembro, usted podrá obtener el dividendo de monedas de invitación de 8%;",
		"invite_gold_x":"Usted obtendrá X monedas de invitación.",
		"invite_case_two":"Caso 1: si usted invita a un amigo a actualizarse para ser miembro gastando 9,99 dólares, obtendrá enseguida la cantidad de monedas de invitación :",
		"invite_nums_grade":"Cantidad de monedas de invitación : importe pagado por el amigo para adquirir la membresía",
		"invite_grade_nowget":"Si invita a los amigos a actualizarse para ser miembro, usted obtendrá enseguida las monedas de invitación;",
		"invite_percent8":"Dividendo de 8%",
		"invite_get_gold400":"Usted obtendrá 400 monedas de invitación",
		"invite_case_one":"Caso 1: si usted invita a un amigo a recargar 10 mil dólares, obtendrá enseguida la cantidad de monedas de invitación :",
		"invite_gold_money":"Cantidad de monedas de invitación : importe recargado por el amigo",
		"invite_now_gold":"Si invita a los amigos a recargar, usted obtendrá enseguida las monedas de invitación;",
		"invite_percent4":"Dividendo de 4%",
		"invite_total_nums":"Número acumulado de personas invitadas",
		"invite_total_reward":"Premios acumulados",
		"invite_error_account":"La cuenta de invitación está bloqueada, no se permite retirar dinero.",
		"invite_normal_account":"La cuenta de invitación está normal.",
		"invite_balance":"Saldo de premio",
		"invite_friend_reward":"Premio devuelto por invitar a amigos",
		"invite_svip_reward":"Premio devuelto por llegar a ser SVIP",
		"invite_vip_reward":"Premio devuelto por llegar a ser VIP",
		"invite_allget_detail":"Detalles de las ganancias del invitador",
		"invite_percent_reward":"Premio de comisión (monedas de invitación)",
		"invite_income_detail":"Detalles de ganancias",
		"invite_time":"Elegir tiempo",
		"invite_download":"Descarga de invitación",
		"copyUrlFont":"El enlace de invitación es copiado exitosamente, envíelo a los amigos a vincular la invitación, con el fin de adquirir ganancias",
		"invite_download_app":"Descargar APP",
		"DownFont":"Descargar APP",
		"invite_register_write":"Rellenar al momento de registrarse",
		"registeredFont":"Rellenar al momento de registrarse",
		"wxFont3":"Luego de ser abierto en el navegador, siga la descarga",
		"wxFont2":"Por favor pulse el rincón superior derecho",
		"wxFont1":"No se puede abrir BothLive en WeChat",
		"Promoter":"Promotor",
		"UserRole":"Papel de usuario",
		"invite_earn_money":"Apresúrese a invitar a los amigos a adquirir ganancias",
		"EarnIncome":"Apresúrese a invitar a los amigos a adquirir ganancias",
		"invite_lasttime":"Tiempo activo último",
		"activeTime":"Tiempo activo último",
		"invite_bindnums":"Número de personas vinculadas",
		"BindNumber":"Número de personas vinculadas",
		"invite_searchid":"Búsqueda de ID",
		"SearchID":"Búsqueda de ID",
		"invite_date":"Fecha",
		"dateFont":"Fecha",
		"RefundStatus":"Estado de devolución de dinero",
		"RefundTime":"Tiempo de devolución de dinero",
		"invite_charge_time":"Tiempo de recarga",
		"RechargeTime":"Tiempo de recarga",
		"Coreward":"Premio de comisión",
		"invite_get_rate":"Proporción de comisión",
		"Coratio":"Proporción de comisión",
		"invite_charge_amount":"Importe neto recargado",
		"NetRechargeAmount":"Importe neto recargado",
		"invite_income_num":"Importe recargado",
		"RechargeAmount":"Importe recargado",
		"invite_paytype":"Tipo de pago",
		"PaymentTypes":"Tipo de pago",
		"invite_chargetype":"Tipo de recarga",
		"TopupType":"Tipo de recarga",
		"invite_friendid":"ID de amigo",
		"BuddyID":"ID de amigo",
		"invite_reset":"Reconfigurar condiciones",
		"ResetCondition":"Reconfigurar condiciones",
		"invite_endtime":"Tiempo de fin",
		"EndTime":"Tiempo de fin",
		"invite_starttime":"Tiempo de inicio",
		"StartTime":"Tiempo de inicio",
		"invite_no_record":"No se ha encontrado el registro pertinente",
		"NoRecording":"No se ha encontrado el registro pertinente",
		"RefundSu":"Devolución de dinero exitosa",
		"invite_reback_gold":"Premio devuelto por la recarga de monedas de oro",
		"goldReturn":"Premio devuelto por la recarga de monedas de oro",
		"invite_charge_percent":"Comisión de recarga",
		"RechargeCommission":"Comisión de recarga",
		"invite_go":"Ir a invitar",
		"ToInvite":"Ir a invitar",
		"invite_rules_con6":"6. En caso de dudas, por favor consulte al personal de servicio al cliente",
		"rules6":"6. En caso de dudas, por favor consulte al personal de servicio al cliente",
		"rules5":"5. El dividendo en efectivo se recibirá en tiempo real;",
		"invite_rules_con4":"4. Si su amigo paga por Apple o Google, como las tienda de Apple y de Google cobran una comisión de 30%, el dividendo se calculará según el importe neto realmente recibido;",
		"rules4":"4. Si su amigo paga por Apple o Google, como las tienda de Apple y de Google cobran una comisión de 30%, el dividendo se calculará según el importe neto realmente recibido;",
		"rules3":"3. Si el amigo invitado recarga, usted podrá obtener el dividendo en efectivo de 5%; si el amigo llega a ser miembro, usted podrá obtener el dividendo en efectivo de 10%;",
		"invite_rules_con2":"2. Usted envía su código de invitación o comparte el enlace de invitación a un amigo; cuando el amigo invitado se registra, rellena el código de invitación para ser vinculado en nombre de usted;",
		"rules2":"2. Usted envía su código de invitación o comparte el enlace de invitación a un amigo; cuando el amigo invitado se registra, rellena el código de invitación para ser vinculado en nombre de usted;",
		"invite_rules_con1":"1. Todos los usuarios pueden tomar parte en el plan de invitación;",
		"rules1":"1. Todos los usuarios pueden tomar parte en el plan de invitación;",
		"invite_rules":"Reglas de invitación",
		"InvitationRules":"Reglas de invitación",
		"CashUpgrade":"Premio en efectivo : importe pagado por el amigo para adquirir la membresía",
		"anlifont22":"Usted obtendrá X dólares.",
		"anlifont21":"Caso 1: si usted invita a un amigo a actualizarse para ser miembro gastando 9,99 dólares, obtendrá enseguida la cantidad de monedas de invitación",
		"Upgrade":"Si invita a los amigos a actualizarse para ser miembro, usted obtendrá enseguida el premio en efectivo:",
		"invite_grade_reward":"Prima de promoción:",
		"UpgradeReward":"Premio de monedas de oro por actualización:",
		"anlifont12":"Usted obtendrá 500 dólares",
		"anlifont11":"Caso 1: si usted invita a un amigo a recargar 10 mil dólares, obtendrá enseguida el premio en efectivo",
		"invite_income_preview":"Vista previa de las ganancias",
		"Preview":"Vista previa de las ganancias",
		"CashReward":"Premio en efectivo : importe recargado por el amigo",
		"Recharge":"Si invita a los amigos a recargar, usted obtendrá enseguida el premio en efectivo.",
		"Commission":"Dividendo",
		"invite_charge_reward":"Premio de la recarga de monedas de oro",
		"GoldReward":"Premio de la recarga de monedas de oro",
		"invite_reward":"Premio de invitación",
		"InvitationReward":"Premio de invitación",
		"invite_peoples":"Número de personas invitadas",
		"inviteNumber":"Número de personas invitadas",
		"invite_income_bills":"Detalles de ganancias",
		"incomeDetail":"Detalles de ganancias",
		"invite_copy":"Copiar",
		"Copy":"Copiar",
		"invite_mycode":"Mi código de invitación",
		"myInviteCode":"Mi código de invitación",
		"invite_intro":"Descripción",
		"invite_from":"Provenir de",
		"goldFrom":"Provenir de",
		"goldFrom":"Provenir de",
		"invite_from":"Provenir de",
		"goldFrom":"Provenir de",
		"invite_from":"Provenir de",
		"invite_get":"Percibir",
		"invite_get":"Percibir",
		"invite_copy_success":"Copia exitosa",
		"CopySuccessfully":"Copia exitosa",
		"AllFont":"Todo",
		"invite_sure":"Confirmar",
		"Rconfirm":"Confirmar",

	}
	
}else if(lang=="ko"){
	interLang_P={
		invite_download : '다운로드 초대',
		invite_mycode : "내 초대 코드",
		invite_copy : '복사',
		invite_register_write : '등록시 기입',
		invite_download_app : '앱 다운로드',
		invite_copy_success : '복사 성공',
		
		
		invite_peoples : '초대받은 사람 수',
		invite_time : '시간 선택',
		invite_searchid : '검색 ID',
		invite_bindnums : '바인딩 번호',
		Invite_lasttime : '마지막 활동 시간',
		invite_earn_money : '돈을 벌기 위해 친구들을 초대하세요',
		invite_starttime : '시작 시간',
		invite_endtime : '종료 시간',
		invite_reset : '조건 재설정',
		invite_sure : '확인',
		invite_date:'데이트',
		
		
		invite_income_detail : '소득 세부 정보',
		invite_friendid : '친구 ID',
		invite_chargetype : '청구 유형',
		invite_paytype : '지불 유형',
		invite_income_num : '충전 금액',
		invite_charge_amount : '재충전 금액',
		invite_get_rate : '수수료율',
		invite_percent_reward : '커미션 보상 (초대 코인)',
		invite_charge_time : '충전 시간',
		invite_allget_detail:'초대 자의 소득 세부 정보',
		invite_income_bills : '소득 세부 정보',
		invite_charge_percent : '충전 수수료',
		invite_from : '보낸 사람',
		invite_no_record : '관련 기록이 없습니다.',
		invite_reback_gold : '골드 코인 충전 및 보상',
		invite_vip_reward : 'VIP 업그레이드 반환 보상',
		invite_svip_reward : 'SVIP 업그레이드 반환 보상',
		
		
		invite_friend_reward:'친구를 초대하여 보상 받기',
		invite_balance : '보상 잔액',
		invite_normal_account : '초대 계정은 정상입니다! ',
		invite_error_account : '초대 계정이 동결되었으며 인출이 허용되지 않습니다! ',
		invite_get : '수신',
		invite_total_reward : '누적 보상',
		invite_total_nums : '총 초대 수',
		invite_reward : '보상 초대',
		invite_charge_reward : '골드 코인 충전 보상',
		invite_percent4 : '4 % 점유율',
		invite_intro : '설명',
		invite_now_gold : '친구를 재충전하도록 초대하면 즉시 초대 코인을 받게됩니다.',
		invite_gold_money : '초대 코인 수 = 친구의 충전량',
		invite_income_preview : '소득 미리보기',
		invite_case_one : 'Case 1 : 친구를 초대하여 미화 10,000 달러를 재충전하면 즉시 초대 코인 개수 =',
		invite_get_gold400 : '초대 코인 400 개를받습니다',
		invite_grade_reward : '회원 업그레이드 보상:',
		invite_percent8 : '8 % 점유율',
		invite_grade_nowget : '멤버십 업그레이드에 친구를 초대하면 즉시 초대 코인을 받게됩니다.',
		invite_nums_grade : '초대 코인 수 = 멤버십을 업그레이드 할 친구 수',
		invite_case_two : 'Case 1 : 친구를 초대하여 멤버십 비용 9.99 USD를 업그레이드하면 즉시 초대 코인 수 =',
		invite_gold_x : '초대 코인 X 개를받습니다. ',
		invite_rules : '초대 규칙',
		invite_rules_con1 : '1. 모든 사용자가 초대 플랜에 참여할 수 있습니다.',
		invite_rules_con2 : '2. 자신의 초대 코드를 보내거나 친구에게 초대 링크를 공유합니다. 초대를 받았을 때, 친구가 등록 할 때 초대 코드를 입력하여 이름을 묶습니다.',
		Invite_rules_con3 : '3. 친구를 재충전하면 초대 코인 4 %, 친구가 멤버로 업그레이드하면 초대 코인 8 %를받을 수 있습니다.',
		invite_rules_con4 : '4. 친구가 Apple 및 Google Pay를 사용하는 경우 Apple Store 및 Google Store에서 처리 수수료 30 %를 부과하므로 실제 수령 한 순 금액을 기준으로 몫이 계산됩니다.',
		invite_rules_con5 : '5. 초대 코인의 몫은 실시간으로 계좌에 입금됩니다.',
		invite_rules_con6 : '6. 문의 사항이 있으시면 고객 센터로 연락주세요',
		invite_go : '초대로 이동',
		invite_copy_href : '초대 링크가 성공적으로 복사되었습니다. 친구에게 보내 초대를 묶어 돈을 벌 수 있습니다.',
		invite_more100 : 'Invite 코인 잔액이 100에 도달하여 소득 신청',
		invite_fun_now : '이 기능은 곧 출시 될 예정입니다.',
		
	}
	
}else if(lang=="vi"){
	interLang_P={
		invite_download:'Mời tải app ',
		invite_mycode:"Mã lời mời của tôi ",
		invite_copy:'Sao chép ',
		invite_register_write:'Điền khi đăng ký tài khoản ',
		invite_download_app:'Tải app ',
		invite_copy_success:'Đã sao chép ',

		
		invite_peoples:'Số người mời ',
		invite_time:'Chọn thời gian ',
		invite_searchid:'Tìm ID',
		invite_bindnums:'Số người gắn kết',
		invite_lasttime:'Thời gian hoạt động cuối cùng ',
		invite_earn_money:'Mau mời bạn bè để nhận thu nhập nào ',
		invite_starttime:'Thời gian bắt đầu ',
		invite_endtime:'Thời gian kết thúc ',
		invite_reset:'Đặt lại điều kiện ',
		invite_sure:'Xác nhận ',
		invite_date:'Ngày tháng ',


		invite_income_detail:'Chi tiết thu nhập ',
		invite_friendid:'ID bạn bè ',
		invite_chargetype:'Loại hình nạp ',
		invite_paytype:'Loại hình thanh toán ',
		invite_income_num:'Số tiền nạp ',
		invite_charge_amount:'Số tiền nạp ròng',
		invite_get_rate:'Tỷ lệ hoa hồng ',
		invite_percent_reward:'Phần thưởng hoa hồng (Gold mời) ',
		invite_charge_time:'Thời gian nạp ',


		invite_allget_detail:'Chi tiết thu nhập của nhân viên mời ',
		invite_income_bills:'Chi tiết thu nhập ',
		invite_charge_percent:'Hoa hồng ',
		invite_from:'đến từ ',
		invite_no_record:'Không tìm thấy thông tin liên quan ',
		invite_reback_gold:'Phần thưởng từ nạp Gold ',
		invite_vip_reward:'Phần thưởng từ nâng cấp VIP ',
		invite_svip_reward:'Phần thưởng từ nâng cấp SVIP ',


		invite_friend_reward:'Phần thưởng khi mời bạn bè ',
		invite_balance:'Số dư phần thưởng ',
		invite_normal_account:'Tài khoản mời bình thường! ',
		invite_error_account:'Tài khoản mời đã bị đóng băng, không thể rút! ',
		invite_get:'Nhận ',
		invite_total_reward:'Tổng phần thưởng',
		invite_total_nums:'Tổng số người mời được ',
		invite_reward:'Phần thưởng mời ',
		invite_charge_reward:'Phần thưởng nạp Gold ',
		invite_percent4:'Tỷ lệ 4% ',
		invite_intro:'Chi tiết ',
		invite_now_gold:'Khi mời bạn bè tải app, bạn sẽ ngay lập tức nhận được Gold mời；',
		invite_gold_money:'Số Gold mời=Số tiền bạn bè nạp vào app ',
		invite_income_preview:'Xem trước thu nhập ',
		invite_case_one:'Ví dụ 1: Người bạn do bạn mời được nạp 10000 USD, bạn sẽ ngay lập tức nhận được số Gold mời = ',
		invite_get_gold400:'Bạn nhận được 400 Gold mời ',
		invite_grade_reward:'Giải nâng cấp thành viên：',
		invite_percent8:'Tỷ lệ 8% ',
		invite_grade_nowget:'Khi mời bạn bè nâng cấp hội viên, bạn sẽ ngay lập tức nhận được Gold mời；',
		invite_nums_grade:'Số gold mời=Số tiền bạn bè nạp để nâng cấp hội viên ',
		invite_case_two:'Ví dụ 1: Người bạn do bạn mời được chi tiêu 9,99 USD, bạn sẽ ngay lập tức nhận được số Gold mời = ',
		invite_gold_x:'Bạn nhận được X Gold mời',
		invite_rules:'Quy tắc mời bạn bè ',
		invite_rules_con1:'1.Tất cả user đều có thể tham gia mời bạn bè; ',
		invite_rules_con2:'2.Hãy gửi mã lời mời hoặc chia sẻ liên kết mời tải app cho bạn bè của mình; Khi người được mời đăng ký tài khoản và nhập mã lời mời, người đó sẽ lập tức được gắn kết cho bạn; ',
		invite_rules_con3:'3.Khi người được mời nạp tiền, bạn có thể nhận được 4% Gold mời; Khi người đó nâng cấp hội viên, bạn sẽ nhận được 8% Gold mời; ',
		invite_rules_con4:'4.Nếu bạn của bạn sử dụng Apple và Google để thanh toán, do cửa hàng ứng dụng của Google và Apple sẽ thu 30% phí thủ tục nên tỷ lệ Gold mời nhận được sẽ tính dựa trên số tiền ròng mà nền tảng nhận được trong thực tế; ',
		invite_rules_con5:'5.Gold mời sẽ được chuyển đến tài khoản của bạn ngay lập tức; ',
		invite_rules_con6:'6.Nếu có bất kỳ thắc mắc vào, vui lòng liên hệ với nhân viên CSKH của chúng tôi ',
		invite_go:'Đi mời ngay ',
		invite_copy_href:'Đã sao chép liên kết mời tải app, gửi cho bạn bè ngay để gắn kết và có thêm thu nhập nào!',
		invite_more100:'Khi đạt 100 Gold mời mới có thể xin nhận thu nhập ',
		invite_fun_now:'Chức năng này sẽ ra mắt trong thời gian tới ',

	}
	
}else if(lang=="fr"){
	interLang_P={
		"invite_fun_now":"Esta función estará en línea pronto",
		"invite_more100":"Para solicitar percibir ganancias, el saldo de monedas de invitación tiene que llegar hasta 100",
		"invite_copy_href":"Éxito de la copia del enlace de invitación",
		"invite_rules_con5":"5. El dividendo de monedas de invitación se recibirá en tiempo real;",
		"invite_rules_con3":"3. Si el amigo invitado recarga, usted podrá obtener un dividendo de monedas de invitación de 4%; si el amigo llega a ser miembro, usted podrá obtener el dividendo de monedas de invitación de 8%;",
		"invite_gold_x":"Usted obtendrá X monedas de invitación.",
		"invite_case_two":"Caso 1: si usted invita a un amigo a actualizarse para ser miembro gastando 9,99 dólares, obtendrá enseguida la cantidad de monedas de invitación =",
		"invite_nums_grade":"Cantidad de monedas de invitación = importe pagado por el amigo para adquirir la membresía",
		"invite_grade_nowget":"Si invita a los amigos a actualizarse para ser miembro, usted obtendrá enseguida las monedas de invitación;",
		"invite_percent8":"Dividendo de 8%",
		"invite_get_gold400":"Usted obtendrá 400 monedas de invitación",
		"invite_case_one":"Caso 1: si usted invita a un amigo a recargar 10 mil dólares, obtendrá enseguida la cantidad de monedas de invitación =",
		"invite_gold_money":"Cantidad de monedas de invitación = importe recargado por el amigo",
		"invite_now_gold":"Si invita a los amigos a recargar, usted obtendrá enseguida las monedas de invitación;",
		"invite_percent4":"Dividendo de 4%",
		"invite_total_nums":"Número acumulado de personas invitadas",
		"invite_total_reward":"Premios acumulados",
		"invite_error_account":"La cuenta de invitación está bloqueada, no se permite retirar dinero.",
		"invite_normal_account":"La cuenta de invitación está normal.",
		"invite_balance":"Saldo de premio",
		"invite_friend_reward":"Premio devuelto por invitar a amigos",
		"invite_svip_reward":"Premio devuelto por llegar a ser SVIP",
		"invite_vip_reward":"Premio devuelto por llegar a ser VIP",
		"invite_allget_detail":"Detalles de las ganancias del invitador",
		"invite_percent_reward":"Premio de comisión (monedas de invitación)",
		"invite_income_detail":"Detalles de ganancias",
		"invite_time":"Elegir tiempo",
		"invite_download":"Descarga de invitación",
		"copyUrlFont":"El enlace de invitación es copiado exitosamente, envíelo a los amigos a vincular la invitación, con el fin de adquirir ganancias",
		"invite_download_app":"Descargar APP",
		"DownFont":"Descargar APP",
		"invite_register_write":"Rellenar al momento de registrarse",
		"registeredFont":"Rellenar al momento de registrarse",
		"wxFont3":"Luego de ser abierto en el navegador, siga la descarga",
		"wxFont2":"Por favor pulse el rincón superior derecho",
		"wxFont1":"No se puede abrir BothLive en WeChat",
		"Promoter":"Promotor",
		"UserRole":"Papel de usuario",
		"invite_earn_money":"Apresúrese a invitar a los amigos a adquirir ganancias",
		"EarnIncome":"Apresúrese a invitar a los amigos a adquirir ganancias",
		"invite_lasttime":"Tiempo activo último",
		"activeTime":"Tiempo activo último",
		"invite_bindnums":"Número de personas vinculadas",
		"BindNumber":"Número de personas vinculadas",
		"invite_searchid":"Búsqueda de ID",
		"SearchID":"Búsqueda de ID",
		"invite_date":"Fecha",
		"dateFont":"Fecha",
		"RefundStatus":"Estado de devolución de dinero",
		"RefundTime":"Tiempo de devolución de dinero",
		"invite_charge_time":"Tiempo de recarga",
		"RechargeTime":"Tiempo de recarga",
		"Coreward":"Premio de comisión",
		"invite_get_rate":"Proporción de comisión",
		"Coratio":"Proporción de comisión",
		"invite_charge_amount":"Importe neto recargado",
		"NetRechargeAmount":"Importe neto recargado",
		"invite_income_num":"Importe recargado",
		"RechargeAmount":"Importe recargado",
		"invite_paytype":"Tipo de pago",
		"PaymentTypes":"Tipo de pago",
		"invite_chargetype":"Tipo de recarga",
		"TopupType":"Tipo de recarga",
		"invite_friendid":"ID de amigo",
		"BuddyID":"ID de amigo",
		"invite_reset":"Reconfigurar condiciones",
		"ResetCondition":"Reconfigurar condiciones",
		"invite_endtime":"Tiempo de fin",
		"EndTime":"Tiempo de fin",
		"invite_starttime":"Tiempo de inicio",
		"StartTime":"Tiempo de inicio",
		"invite_no_record":"No se ha encontrado el registro pertinente",
		"NoRecording":"No se ha encontrado el registro pertinente",
		"RefundSu":"Devolución de dinero exitosa",
		"invite_reback_gold":"Premio devuelto por la recarga de monedas de oro",
		"goldReturn":"Premio devuelto por la recarga de monedas de oro",
		"invite_charge_percent":"Comisión de recarga",
		"RechargeCommission":"Comisión de recarga",
		"invite_go":"Ir a invitar",
		"ToInvite":"Ir a invitar",
		"invite_rules_con6":"6. En caso de dudas, por favor consulte al personal de servicio al cliente",
		"rules6":"6. En caso de dudas, por favor consulte al personal de servicio al cliente",
		"rules5":"5. El dividendo en efectivo se recibirá en tiempo real;",
		"invite_rules_con4":"4. Si su amigo paga por Apple o Google, como las tienda de Apple y de Google cobran una comisión de 30%, el dividendo se calculará según el importe neto realmente recibido;",
		"rules4":"4. Si su amigo paga por Apple o Google, como las tienda de Apple y de Google cobran una comisión de 30%, el dividendo se calculará según el importe neto realmente recibido;",
		"rules3":"3. Si el amigo invitado recarga, usted podrá obtener el dividendo en efectivo de 5%; si el amigo llega a ser miembro, usted podrá obtener el dividendo en efectivo de 10%;",
		"invite_rules_con2":"2. Usted envía su código de invitación o comparte el enlace de invitación a un amigo; cuando el amigo invitado se registra, rellena el código de invitación para ser vinculado en nombre de usted;",
		"rules2":"2. Usted envía su código de invitación o comparte el enlace de invitación a un amigo; cuando el amigo invitado se registra, rellena el código de invitación para ser vinculado en nombre de usted;",
		"invite_rules_con1":"1. Todos los usuarios pueden tomar parte en el plan de invitación;",
		"rules1":"1. Todos los usuarios pueden tomar parte en el plan de invitación;",
		"invite_rules":"Reglas de invitación",
		"InvitationRules":"Reglas de invitación",
		"CashUpgrade":"Premio en efectivo = importe pagado por el amigo para adquirir la membresía",
		"anlifont22":"Usted obtendrá X dólares.",
		"anlifont21":"Caso 1: si usted invita a un amigo a actualizarse para ser miembro gastando 9,99 dólares, obtendrá enseguida la cantidad de monedas de invitación",
		"Upgrade":"Si invita a los amigos a actualizarse para ser miembro, usted obtendrá enseguida el premio en efectivo:",
		"invite_grade_reward":"Prime de promotion:",
		"UpgradeReward":"Premio de monedas de oro por actualización:",
		"anlifont12":"Usted obtendrá 500 dólares",
		"anlifont11":"Caso 1: si usted invita a un amigo a recargar 10 mil dólares, obtendrá enseguida el premio en efectivo",
		"invite_income_preview":"Vista previa de las ganancias",
		"Preview":"Vista previa de las ganancias",
		"CashReward":"Premio en efectivo = importe recargado por el amigo",
		"Recharge":"Si invita a los amigos a recargar, usted obtendrá enseguida el premio en efectivo.",
		"Commission":"Dividendo",
		"invite_charge_reward":"Premio de la recarga de monedas de oro",
		"GoldReward":"Premio de la recarga de monedas de oro",
		"invite_reward":"Premio de invitación",
		"InvitationReward":"Premio de invitación",
		"invite_peoples":"Número de personas invitadas",
		"inviteNumber":"Número de personas invitadas",
		"invite_income_bills":"Detalles de ganancias",
		"incomeDetail":"Detalles de ganancias",
		"invite_copy":"Copiar",
		"Copy":"Copiar",
		"invite_mycode":"Mi código de invitación",
		"myInviteCode":"Mi código de invitación",
		"invite_intro":"Descripción",
		"Description":"Descripción",
		"invite_from":"Provenir de",
		"goldFrom":"Provenir de",
		"goldFrom":"Provenir de",
		"invite_from":"Provenir de",
		"goldFrom":"Provenir de",
		"invite_from":"Provenir de",
		"invite_get":"Percibir",
		"invite_get":"Percibir",
		"invite_copy_success":"Copia exitosa",
		"CopySuccessfully":"Copia exitosa",
		"AllFont":"Todo",
		"invite_sure":"Confirmar",
		"Rconfirm":"Confirmar",
	}
	
}else if(lang=="pt"){
	interLang_P={
		"invite_fun_now":"Este recurso será lançado em breve",
		"invite_more100":"Somente quando o saldo de moedas de convite chegar a 100 você poderá reivindicar a renda",
		"invite_copy_href":"Copie o link do convite para",
		"invite_rules_con5":"5. A quota de moedas de convite será creditada na conta em tempo real;",
		"invite_rules_con3":"3. Se o amigo convidado recarregar, você pode obter 4% das moedas de convite; se o amigo atualizar o membro, você pode obter 8% das moedas de convite;",
		"invite_gold_x":"Você ganha X moedas de convite.",
		"invite_case_two":"Exemplo 1: se você convidar um amigo para atualizar membro, custa US $9,99 e você receberá imediatamente a quantidade de moedas de convite =",
		"invite_nums_grade":"Quantidade de moedas de convite = quantia de atualização de membro",
		"invite_grade_nowget":"Convide amigos para atualizar o membro, você receberá moedas de convite imediatamente;",
		"invite_percent8":"8% de participação",
		"invite_get_gold400":"Você ganha 400 moedas de convite",
		"invite_case_one":"Exemplo 1: você convida um amigo para recarregar US $10.000 e receberá imediatamente um prémio em dinheiro =",
		"invite_gold_money":"Número de moedas de convite = quantia de recarga de amigo",
		"invite_now_gold":"Convide amigos para recarregar e você receberá moedas de convite imediatamente;",
		"invite_percent4":"4% de participação",
		"invite_total_nums":"Número cumulativo de convites",
		"invite_total_reward":"Prémio cumulativo",
		"invite_error_account":"A conta do convite foi congelada e nenhum saque será permitido!",
		"invite_normal_account":"A conta do convite está normal!",
		"invite_balance":"Saldo de prémio",
		"invite_friend_reward":"Convidar amigos para obter prémios",
		"invite_svip_reward":"Prémio de atualização de SVIP",
		"invite_vip_reward":"Prémio de atualização de VIP",
		"invite_allget_detail":"Detalhes de renda do convidado",
		"invite_percent_reward":"Prémio da comissão (moeda do convite)",
		"invite_income_detail":"Detalhes da renda",
		"invite_time":"Seleção de tempo",
		"invite_download":"Convidar download",
		"copyUrlFont":"O link do convite foi copiado, envie-o a um amigo para vincular o convite e ganhar renda",
		"invite_download_app":"Baixar aplicativo",
		"DownFont":"Baixar aplicativo",
		"invite_register_write":"Preencha ao se inscrever",
		"registeredFont":"Preencha ao se inscrever",
		"wxFont3":"Escolha continuar o download após abrir o navegador",
		"wxFont2":"Clique no canto superior direito",
		"wxFont1":"Não é possível abrir o BothLive no WeChat",
		"Promoter":"Promotor",
		"UserRole":"Personagem do usuário",
		"invite_earn_money":"Vá convidar amigos para ganhar dinheiro",
		"EarnIncome":"Vá convidar amigos para ganhar dinheiro",
		"invite_lasttime":"Tempo da última vez",
		"activeTime":"Tempo da última vez",
		"invite_bindnums":"Número de pessoas vinculadas",
		"BindNumber":"Número de pessoas vinculadas",
		"invite_searchid":"ID de pesquisa",
		"SearchID":"ID de pesquisa",
		"invite_date":"Data",
		"dateFont":"Data",
		"RefundStatus":"Status de reembolso",
		"RefundTime":"Tempo de reembolso",
		"invite_charge_time":"Tempo de recarga",
		"RechargeTime":"Tempo de recarga",
		"Coreward":"Prémio de comissão",
		"invite_get_rate":"Relação de comissão",
		"Coratio":"Relação de comissão",
		"invite_charge_amount":"Valor líquido de recarga",
		"NetRechargeAmount":"Valor líquido de recarga",
		"invite_income_num":"Quantidade de recarga",
		"RechargeAmount":"Quantidade de recarga",
		"invite_paytype":"Tipo de pagamento",
		"PaymentTypes":"Tipo de pagamento",
		"invite_chargetype":"Tipo de recarga",
		"TopupType":"Tipo de recarga",
		"invite_friendid":"ID de amigo",
		"BuddyID":"ID de amigo",
		"invite_reset":"Condição de redefinição",
		"ResetCondition":"Condição de redefinição",
		"invite_endtime":"Tempo de fim",
		"EndTime":"Tempo de fim",
		"invite_starttime":"Tempo de início",
		"StartTime":"Tempo de início",
		"invite_no_record":"Nenhum registro relevante foi encontrado",
		"NoRecording":"Nenhum registro relevante foi encontrado",
		"RefundSu":"Reembolsado",
		"invite_reback_gold":"Prémio de recarga de moedas de ouro",
		"goldReturn":"Prémio de recarga de moedas de ouro",
		"invite_charge_percent":"Comissão de recarga",
		"RechargeCommission":"Comissão de recarga",
		"invite_go":"Vá convidar",
		"ToInvite":"Vá convidar",
		"invite_rules_con6":"6. Se você tiver alguma dúvida, entre em contato com o atendimento ao cliente",
		"rules6":"6. Se você tiver alguma dúvida, entre em contato com o atendimento ao cliente",
		"rules5":"5. A parcela em dinheiro será creditada na conta em tempo real;",
		"invite_rules_con4":"4. Se seu amigo usa Apple e Google Pay, devido a Apple Store e a Google Store cobrarão uma taxa de 30%, a parcela será calculada com base no valor líquido real recebido;",
		"rules4":"4. Se seu amigo usa Apple e Google Pay, devido a Apple Store e a Google Store cobrarão uma taxa de 30%, a parcela será calculada com base no valor líquido real recebido;",
		"rules3":"3. Se o amigo convidado recarregar, você pode obter 5% de participação em dinheiro; se o amigos atualizar o membro, você pode obter 10% de participação em dinheiro;",
		"invite_rules_con2":"2. Você envia seu próprio código de convite ou compartilha o link de convite com seus amigos; quando o amigo convidado se registrar, preencha o código de convite para vincular ao seu nome;",
		"rules2":"2. Você envia seu próprio código de convite ou compartilha o link de convite com seus amigos; quando o amigo convidado se registrar, preencha o código de convite para vincular ao seu nome;",
		"invite_rules_con1":"1. Todos os usuários podem participar do plano de convite;",
		"rules1":"1. Todos os usuários podem participar do plano de convite;",
		"invite_rules":"Regras de convite",
		"InvitationRules":"Regras de convite",
		"CashUpgrade":"Prémio em dinheiro = quantia de atualização de membro",
		"anlifont22":"Você ganha X dólares.",
		"anlifont21":"Exemplo 1: se você convidar um amigo para atualizar membro, custa US $9,99 e você receberá imediatamente a quantidade de moedas de convite",
		"Upgrade":"Convide um amigo para atualizar membro, você receberá um prémio em dinheiro imediatamente:",
		"invite_grade_reward":"Prémio de actualização DOS Estados-Membros:",
		"UpgradeReward":"Prémios de atualização de moedas de ouro:",
		"anlifont12":"Você ganha 500 dólares",
		"anlifont11":"Exemplo 1: você convida um amigo para recarregar US $10.000 e receberá imediatamente um prémio em dinheiro",
		"invite_income_preview":"Visualização da renda",
		"Preview":"Visualização da renda",
		"CashReward":"Prémio em dinheiro = Valor de recarga de amigos",
		"Recharge":"Convide amigos para recarregar e você receberá prémios em dinheiro imediatamente:",
		"Commission":"Proporção retida",
		"invite_charge_reward":"Prémio de recarga de moedas de ouro",
		"GoldReward":"Prémio de recarga de moedas de ouro",
		"invite_reward":"Prémio de convite",
		"InvitationReward":"Prémio de convite",
		"invite_peoples":"Número de convite",
		"inviteNumber":"Número de convite",
		"invite_income_bills":"Composição da renda",
		"incomeDetail":"Composição da renda",
		"invite_copy":"Cópia",
		"Copy":"Cópia",
		"invite_mycode":"Meu código de convite",
		"myInviteCode":"Meu código de convite",
		"invite_intro":"Descrição",
		"Description":"Descrição",
		"invite_from":"De",
		"goldFrom":"De",
		"goldFrom":"De",
		"invite_from":"De",
		"goldFrom":"De",
		"invite_from":"De",
		"invite_get":"Receber",
		"invite_get":"Receber",
		"invite_copy_success":"Copiar",
		"CopySuccessfully":"Copiar",
		"AllFont":"Tudo",
		"invite_sure":"Confirmar",
		"Rconfirm":"Confirmar",
	}
	
}else if(lang=="de"){
	interLang_P={
		"invite_fun_now":"Diese Funktion wird demnächst eingeführt",
		"invite_more100":"Erst wenn der Saldo der Einladungsmünzen 100 erreicht, können Sie das Einkommen beantragen",
		"invite_copy_href":"Kopieren des Einladungslinks erfolgreich",
		"invite_rules_con5":"5. Der Anteil der Einladungsmünzen wird dem Konto in Echtzeit gutgeschrieben;",
		"invite_rules_con3":"3. Eingeladene Freunde zum Aufladen können 4% der Einladungsmünzen erhalten; Freunde können die Mitgliedschaft erweitern, Sie erhalten 8% der Einladungsmünzen;",
		"invite_gold_x":"Sie erhalten X Einladungsmünzen.",
		"invite_case_two":"Fall 1: Wenn Sie einen Freund einladen, die Mitgliedschaft zu erweitern, kostet dies $9,99, und Sie erhalten sofort die Anzahl der Einladungsmünzen =",
		"invite_nums_grade":"Die Anzahl der Einladungsmünzen = Die Anzahl der Freunde, die die Mitgliedschaft erweitern",
		"invite_grade_nowget":"Laden Sie Freunde ein, die Mitgliedschaft erweitern, Sie erhalten sofort Einladungsmünzen;",
		"invite_percent8":"8% Anteil",
		"invite_get_gold400":"Sie erhalten 400 Einladungsmünzen",
		"invite_case_one":"Fall 1: Sie laden einen Freund ein, um 10.000 USD aufzuladen, und Sie erhalten sofort die Anzahl der Einladungsmünzen =",
		"invite_gold_money":"Anzahl der Einladungsmünzen = Aufladebetrag für Freunde",
		"invite_now_gold":"Laden Sie Freunde zum Aufladen ein und Sie erhalten sofort Einladungsmünzen;",
		"invite_percent4":"4% Anteil",
		"invite_total_nums":"Kumulative Anzahl von Einladungen",
		"invite_total_reward":"Kumulative Belohnung",
		"invite_error_account":"Das Einladungskonto wurde eingefroren und eine Abhebung ist nicht möglich!",
		"invite_normal_account":"Das Einladungskonto ist normal!",
		"invite_balance":"Saldo der Belohnung",
		"invite_friend_reward":"Freunde einladen, um Belohnungen zu erhalten",
		"invite_svip_reward":"SVIP-Upgrade-Belohnungen",
		"invite_vip_reward":"VIP-Upgrade- Belohnungen",
		"invite_allget_detail":"Details zum Einkommen des Einladers",
		"invite_percent_reward":"Kommission-Belohnung (Einladungsmünze)",
		"invite_income_detail":"Details des Einkommens",
		"invite_time":"Auswahlzeitraum",
		"invite_download":"Herunterladen einladen",
		"copyUrlFont":"Wenn der Einladungslink erfolgreich kopiert wurde, senden Sie ihn an einen Freund, um die Einladung zum Geldverdienen zu binden",
		"invite_download_app":"APP herunterladen",
		"DownFont":"APP herunterladen",
		"invite_register_write":"Bei der Registrierung ausfüllen",
		"registeredFont":"Bei der Registrierung ausfüllen",
		"wxFont3":"Wählen Sie, ob der Download nach dem Öffnen des Browsers fortgesetzt werden soll",
		"wxFont2":"Bitte klicken Sie auf die obere rechte Ecke",
		"wxFont1":"BothLive in WeChat kann nicht geöffnet werden",
		"Promoter":"Förderer",
		"UserRole":"Benutzer-Rolle",
		"invite_earn_money":"Beeilen Sie sich und laden Sie Freunde ein, Geld zu verdienen",
		"EarnIncome":"Beeilen Sie sich und laden Sie Freunde ein, Geld zu verdienen",
		"invite_lasttime":"Letzte aktive Zeit",
		"activeTime":"Letzte aktive Zeit",
		"invite_bindnums":"Anzahl der gebundenen Personen",
		"BindNumber":"Anzahl der gebundenen Personen",
		"invite_searchid":"ID suchen",
		"SearchID":"ID suchen",
		"invite_date":"Datum",
		"dateFont":"Datum",
		"RefundStatus":"Status der Rückerstattung",
		"RefundTime":"Rückerstattungszeit",
		"invite_charge_time":"Aufladezeit",
		"RechargeTime":"Aufladezeit",
		"Coreward":"Kommission-Belohnung",
		"invite_get_rate":"Kommissionsquote",
		"Coratio":"Kommissionsquote",
		"invite_charge_amount":"Netto-Aufladebetrag",
		"NetRechargeAmount":"Netto-Aufladebetrag",
		"invite_income_num":"Aufladebetrag",
		"RechargeAmount":"Aufladebetrag",
		"invite_paytype":"Zahlungsarten",
		"PaymentTypes":"Zahlungsarten",
		"invite_chargetype":"Auflade-Typ",
		"TopupType":"Auflade-Typ",
		"invite_friendid":"Freund-ID",
		"BuddyID":"Freund-ID",
		"invite_reset":"Zustand von Reset",
		"ResetCondition":"Zustand von Reset",
		"invite_endtime":"Endzeit",
		"EndTime":"Endzeit",
		"invite_starttime":"Startzeit",
		"StartTime":"Startzeit",
		"invite_no_record":"Es wurden keine relevanten Aufzeichnungen gefunden",
		"NoRecording":"Es wurden keine relevanten Aufzeichnungen gefunden",
		"RefundSu":"Rückerstattung erfolgreich",
		"invite_reback_gold":"Belohnungen zum Aufladen von Goldmünzen",
		"goldReturn":"Belohnungen zum Aufladen von Goldmünzen",
		"invite_charge_percent":"Kommission für Aufladung",
		"RechargeCommission":"Kommission für Aufladung",
		"invite_go":"Einladen",
		"ToInvite":"Einladen",
		"invite_rules_con6":"6. Wenn Sie Fragen haben, wenden Sie sich bitte an den Kundendienst",
		"rules6":"6. Wenn Sie Fragen haben, wenden Sie sich bitte an den Kundendienst",
		"rules5":"5. Der Bargeldanteil wird dem Konto in Echtzeit gutgeschrieben;",
		"invite_rules_con4":"4. Wenn Ihre Freunde Apple und Google Pay verwenden, da Apple Store und Google Store eine Bearbeitungsgebühr von 30% erheben, wird der Anteil auf der Grundlage des tatsächlich erhaltenen Nettobetrags berechnet;",
		"rules4":"4. Wenn Ihre Freunde Apple und Google Pay verwenden, da Apple Store und Google Store eine Bearbeitungsgebühr von 30% erheben, wird der Anteil auf der Grundlage des tatsächlich erhaltenen Nettobetrags berechnet;",
		"rules3":"3. Eingeladene Freunde zum Aufladen können Sie 5% Bargeldanteil erhalten; Freunde, die eine Upgrade-Mitgliedschaft erwerben, können 10% Bargeldanteil erhalten;",
		"invite_rules_con2":"2. Sie senden Ihren eigenen Einladungscode oder geben den Einladungslink an Ihre Freunde weiter; wenn sie zur Registrierung eingeladen werden, geben den Einladungscode ein, um sich an Ihren Namen zu binden;",
		"rules2":"2. Sie senden Ihren eigenen Einladungscode oder geben den Einladungslink an Ihre Freunde weiter; wenn sie zur Registrierung eingeladen werden, geben den Einladungscode ein, um sich an Ihren Namen zu binden;",
		"invite_rules_con1":"1. Alle Benutzer können am Einladungsplan teilnehmen;",
		"rules1":"1. Alle Benutzer können am Einladungsplan teilnehmen;",
		"invite_rules":"Einladungsregeln",
		"InvitationRules":"Einladungsregeln",
		"CashUpgrade":"Bargeld-Belohnung = Betrag für Freunde zur Aufwertung der Mitgliedschaft",
		"anlifont22":"Sie haben X Dollar.",
		"anlifont21":"Fall 1: Wenn Sie einen Freund einladen, die Mitgliedschaft zu erweitern, kostet dies $9,99, und Sie erhalten sofort die Anzahl der Einladungsmünzen",
		"Upgrade":"Laden Sie Freunde zu einer Upgrade-Mitgliedschaft ein, Sie erhalten sofort Bargeld-Belohnung:",
		"invite_grade_reward":"Auszeichnung für Mitglieder:",
		"UpgradeReward":"Goldmünzen-Upgrade-Belohnungen:",
		"anlifont12":"Sie erhalten 500 Dollar",
		"anlifont11":"Fall 1: Sie laden einen Freund ein, 10.000 USD aufzuladen, und Sie erhalten sofort eine Bargeld-Belohnung",
		"invite_income_preview":"Einkommensvorschau",
		"Preview":"Einkommensvorschau",
		"CashReward":"Bargeld-Belohnung = Betrag der Aufladung von Freunden",
		"Recharge":"Laden Sie Freunde ein, und Sie erhalten sofort eine Bargeld-Belohnung:",
		"Commission":"Aufgeteilt in",
		"invite_charge_reward":"Belohnungen zum Aufladen von Goldmünzen",
		"GoldReward":"Belohnungen zum Aufladen von Goldmünzen",
		"invite_reward":"Einladung-Belohnung",
		"InvitationReward":"Einladung-Belohnung",
		"invite_peoples":"Anzahl der Einladungen",
		"inviteNumber":"Anzahl der Einladungen",
		"invite_income_bills":"Details des Einkommens",
		"incomeDetail":"Details des Einkommens",
		"invite_copy":"Kopie",
		"Copy":"Kopie",
		"invite_mycode":"Mein Einladungscode",
		"myInviteCode":"Mein Einladungscode",
		"invite_intro":"Beschreibung",
		"Description":"Beschreibung",
		"invite_from":"Von",
		"goldFrom":"Von",
		"goldFrom":"Von",
		"invite_from":"Von",
		"goldFrom":"Von",
		"invite_from":"Von",
		"invite_get":"Erhalten",
		"invite_get":"Erhalten",
		"invite_copy_success":"Kopieren erfolgreich",
		"CopySuccessfully":"Kopieren erfolgreich",
		"AllFont":"Alle",
		"invite_sure":"Bestätigen",
		"Rconfirm":"Bestätigen",
	}
	
}else if(lang=="ar"){
	interLang_P={
		"invite_fun_now":"تكون هذه الوظيفة على وشك أولاين",
		"invite_more100":"لا يمكن طلب الحصول على دخل إلا برصيد نقود الدعوة 100",
		"invite_copy_href":"تنسيخ وصلة الدعوة",
		"invite_rules_con5":"5. تصل نقود الدعوة إلى الحساب في الوقت الحقيقي؛",
		"invite_rules_con3":"3. يشحن الصديق المدعو، تحصل على عمولة نقود الدعوة 4%؛ يرقي الصديق العضوية، تحصل على عمولة 8% نقود دعوة؛",
		"invite_gold_x":"تحصل على X نقود دعوة.",
		"invite_case_two":"=القضية الأولى: يصرف الصديق المدعو 9.99 دولار في ترقية العضوية، تحصل على عدد نقود الدعوة فورا",
		"invite_nums_grade":"عدد نقود الدعوة = قيمة ترقية العضوية بالصديق",
		"invite_grade_nowget":"بعد دعوة الصديق لترقية العضوية، تحصل على نقود الدعوة فورا؛",
		"invite_percent8":"8% عمولة",
		"invite_get_gold400":"تحصل على 400 نقد دعوة",
		"invite_case_one":"=القضية الأولى: تدعو الصديق لشحن عشرة آلاف دولار، تحصل على عدد نقود الدعوة فورا ",
		"invite_gold_money":"عدد الأصدقاء المدعو = قيمة شحن الصديق",
		"invite_now_gold":"دعوة الصديق للشحن، تحصل على نقود الدعوة فورا؛",
		"invite_percent4":"4%عمولة ",
		"invite_total_nums":"عدد الأفراد المدعو المتراكم",
		"invite_total_reward":"مكافآت متراكمة",
		"invite_error_account":"تم تجميد حساب الدعوة، لا يمكن السحب!",
		"invite_normal_account":"حساب الدعوة طبيعي!",
		"invite_balance":"رصيد المكافآت",
		"invite_friend_reward":"مكافآت دعوة الصديق",
		"invite_svip_reward":"SVIPمكافآت ترقية ",
		"invite_vip_reward":"مكافآت ترقية VIP",
		"invite_allget_detail":"تفصيل دخل الدعوة",
		"invite_percent_reward":"مكافآت العمولة (نقود الدعوو)",
		"invite_income_detail":"تفصيل الدخل",
		"invite_time":"خيار الوقت",
		"invite_download":"دعوة التنزيل",
		"copyUrlFont":"تم تنسيخ وصلة الدعوة، أرسلها إلى الصديق لربط الدعوة لكسب الدخل",
		"invite_download_app":"تنزيل آب",
		"DownFont":"تنزيل آب",
		"invite_register_write":"يكتب عند التسجيل",
		"registeredFont":"يكتب عند التسجيل",
		"wxFont3":"بعد خيار الفتح بالمتصفح، يواصل التنزيل",
		"wxFont2":"انقر الزاوية اليمنى العليا",
		"wxFont1":"لا يمكن فتح BothLive في ويتشات",
		"Promoter":"مروج",
		"UserRole":"شخصية المستخدم",
		"invite_earn_money":"هيا دعوة الصديق لكسب الدخل",
		"EarnIncome":"هيا دعوة الصديق لكسب الدخل",
		"invite_lasttime":"آخر وقت نشيط",
		"activeTime":"آخر وقت نشيط",
		"invite_bindnums":"عدد الأفراد المربوط",
		"BindNumber":"عدد الأفراد المربوط",
		"invite_searchid":"بحث الحساب",
		"SearchID":"بحث الحساب",
		"invite_date":"التاريخ",
		"dateFont":"التاريخ",
		"RefundStatus":"وضع الاسترداد",
		"RefundTime":"وقت الاسترداد",
		"invite_charge_time":"وقت الشحن",
		"RechargeTime":"وقت الشحن",
		"Coreward":"مكافآت العمولة",
		"invite_get_rate":"نسبة العمولة",
		"Coratio":"نسبة العمولة",
		"invite_charge_amount":"القيمة الصافية للشحن",
		"NetRechargeAmount":"القيمة الصافية للشحن",
		"invite_income_num":"قيمة الشحن",
		"RechargeAmount":"قيمة الشحن",
		"invite_paytype":"نوع الدفع",
		"PaymentTypes":"نوع الدفع",
		"invite_chargetype":"نوع الشحن",
		"TopupType":"نوع الشحن",
		"invite_friendid":"حساب الصديق",
		"BuddyID":"حساب الصديق",
		"invite_reset":"شروط إعادة الإعدادات",
		"ResetCondition":"شروط إعادة الإعدادات",
		"invite_endtime":"وقت الانتهاء",
		"EndTime":"وقت الانتهاء",
		"invite_starttime":"وقت البدأ",
		"StartTime":"وقت البدأ",
		"invite_no_record":"لم تجد السجل المتعلقة",
		"NoRecording":"لم تجد السجل المتعلقة",
		"RefundSu":"تم استرداد",
		"invite_reback_gold":"مكافآت رجوع قيمة الشحن",
		"goldReturn":"مكافآت رجوع قيمة الشحن",
		"invite_charge_percent":"عمولة الشحن",
		"RechargeCommission":"عمولة الشحن",
		"invite_go":"دعوة",
		"ToInvite":"دعوة",
		"invite_rules_con6":"6. إن كان السؤال فاستفسر الخدمة",
		"rules6":"6. إن كان السؤال فاستفسر الخدمة",
		"rules5":"5. تصل العمولة النقدية إلى الحساب في الوقت الحقيقي؛ ",
		"invite_rules_con4":"4. إذا استعمل صديقك دفع آبل وجوجل، لأن متجر آبل ومتجر جوجل يحصل 30% رسوم الإجراءات، يحسب العمولة حسب المبلغ الصافي الذي يصل إلى الحساب فاعليا؛",
		"rules4":"4. إذا استعمل صديقك دفع آبل وجوجل، لأن متجر آبل ومتجر جوجل يحصل 30% رسوم الإجراءات، يحسب العمولة حسب المبلغ الصافي الذي يصل إلى الحساب فاعليا؛",
		"rules3":"3. يمكنكم على توزيع نقدي 5% بشحن الصديق المدعو؛ تحصل على توزيع نقدي 10% بترقية الصديق للعضوية؛",
		"invite_rules_con2":"2. ترسل رمز الدعوة الخاص لكم أو تشارك وصلة الدعوة إلى الصديق؛ عند تسجيل الصديق المدعو، اكتب رمز الدعوة للربط في اسمكم؛",
		"rules2":"2. ترسل رمز الدعوة الخاص لكم أو تشارك وصلة الدعوة إلى الصديق؛ عند تسجيل الصديق المدعو، اكتب رمز الدعوة للربط في اسمكم؛",
		"invite_rules_con1":"1. يمكن لجميع المستخدمين المشاركة في خطة الدعوة؛",
		"rules1":"1. يمكن لجميع المستخدمين المشاركة في خطة الدعوة؛",
		"invite_rules":"قواعد الدعوة",
		"InvitationRules":"قواعد الدعوة",
		"CashUpgrade":"المكافت النقدية = قيمة ترقية العضوية بالصديق",
		"anlifont22":"تحصل على دولار أمريكي X",
		"anlifont21":"القضية الأولى: تصرف 9.99 دولار لدعوة الصديق في ترقية العضوية، تحصل على عدد نقود الدعوة",
		"Upgrade":"بعد دعوة الصديق لترقية العضوية، تحصل على المكافآت النقدية فورا:",
		"invite_grade_reward":":ترقية الأعضاء مكافأة",
		"UpgradeReward":"مكافآت ترقية النقود:",
		"anlifont12":"تحصل على خمسمائات دولار",
		"anlifont11":"القضية الأولى: تحصل على المكفآت النقدية فورا بعد دعوتكم للصديق في شحن عشرة آلاف دولار أمريكي",
		"invite_income_preview":"عرض الدخل",
		"Preview":"عرض الدخل",
		"CashReward":"المكافآت النقدية = قيمة الشحن للصديق",
		"Recharge":"بعد دعوة الصديق للشحن، تحصل على مكافآت نقدية فورا:",
		"Commission":"عمولة",
		"invite_charge_reward":"مكافأة شحن النقود",
		"GoldReward":"مكافأة شحن النقود",
		"invite_reward":"مكافآت الدعوة",
		"InvitationReward":"مكافآت الدعوة",
		"invite_peoples":"عدد الأفراد المدعو",
		"inviteNumber":"عدد الأفراد المدعو",
		"invite_income_bills":"تفصيل الدخل",
		"incomeDetail":"تفصيل الدخل",
		"invite_copy":"تنسيخ",
		"Copy":"تنسيخ",
		"invite_mycode":"رمز الدعوة",
		"myInviteCode":"رمز الدعوة",
		"invite_intro":"وصف",
		"Description":"",
		"invite_from":"من",
		"goldFrom":"",
		"invite_get":"تسلم",
		"invite_copy_success":"نسخة ناجحة",
		"CopySuccessfully":"",
		"AllFont":"",
		"invite_sure":"أكد",
		"Rconfirm":"",
	}
}else if(lang=="zhtw"){
	interLang_P={
		invite_download:'邀請下載',
		invite_mycode:"我的邀請碼",
		invite_copy:'複製',
		invite_register_write:'註冊時填寫',
		invite_download_app:'下載APP',
		invite_copy_success:'複製成功',

		
		invite_peoples:'邀請人數',
		invite_time:'選擇時間',
		invite_searchid:'蒐索ID',
		invite_bindnums:'綁定人數',
		invite_lasttime:'最後活躍時間',
		invite_earn_money:'快去邀請好友賺取收益',
		invite_starttime:'開始時間',
		invite_endtime:'結束時間',
		invite_reset:'重置條件',
		invite_sure:'確認',
		invite_date:'日期',


		invite_income_detail:'收益詳情',
		invite_friendid:'好友ID',
		invite_chargetype:'充值類型',
		invite_paytype:'支付類型',
		invite_income_num:'充值金額',
		invite_charge_amount:'充值金額淨額',
		invite_get_rate:'提成比例',
		invite_percent_reward:'提成獎勵（邀請幣）',
		invite_charge_time:'充值時間',


		invite_allget_detail:'邀請員收益明細',
		invite_income_bills:'收益明細',
		invite_charge_percent:'充值提成',
		invite_from:'來自',
		invite_no_record:'沒有找到相關記錄',
		invite_reback_gold:'金幣充值返還獎勵',
		invite_vip_reward:'VIP陞級返還獎勵',
		invite_svip_reward:'SVIP陞級返還獎勵',


		invite_friend_reward:'邀請好友返獎勵',
		invite_balance:'獎勵餘額',
		invite_normal_account:'邀請帳號正常！',
		invite_error_account:'邀請帳號已被凍結，不予提現！',
		invite_get:'領取',
		invite_total_reward:'累計獎勵',
		invite_total_nums:'累計邀請人數',
		invite_reward:'邀請獎勵',
		invite_charge_reward:'金幣充值獎勵',
		invite_percent4:'4%分成',
		invite_intro:'說明',
		invite_now_gold:'邀請好友充值，您將立即獲得邀請幣；',
		invite_gold_money:'邀請幣數量=好友充值金額',
		invite_income_preview:'收益預演',
		invite_case_one:'案例1：您邀請好友充值1萬美元，您將立即獲得邀請幣數量=',
		invite_get_gold400:'您得400邀請幣',
		invite_grade_reward:'會員陞級獎勵：',
		invite_percent8:'8%分成',
		invite_grade_nowget:'邀請好友陞級會員，您將立即獲得邀請幣；',
		invite_nums_grade:'邀請幣數量=好友陞級會員金額',
		invite_case_two:'案例1：您邀請好友陞級會員花費9.99美元，您將立即獲得邀請幣數量=',
		invite_gold_x:'您得X邀請幣。',
		invite_rules:'邀請規則',
		invite_rules_con1:'1.所有用戶都可參與邀請計畫；',
		invite_rules_con2:'2.您發送自己的邀請碼或者分享邀請連結至好友；被邀請好友註冊時，填入邀請碼，即可綁定至您名下；',
		invite_rules_con3:'3.被邀請好友充值，您可獲得4%邀請幣分成；好友陞級會員，您可獲得8%邀請幣分成；',
		invite_rules_con4:'4.如果您的好友使用蘋果和穀歌支付，因蘋果商店和穀歌商店會收取30%手續費，分成會按照實際到賬的淨額來計算；',
		invite_rules_con5:'5.邀請幣分成將實时到賬；',
		invite_rules_con6:'6.如有疑問，請諮詢客服',
		invite_go:'去邀請',
		invite_copy_href:'邀請連結複製成功，發送給朋友綁定邀請賺取收益吧',
		invite_more100:'邀請幣餘額達到100才能申請領取收益',
		invite_fun_now:'該功能即將上線',
	}
}else{
	interLang_P={
		invite_download:'Invite to download',
		invite_mycode:"My invitation code",
		invite_copy:'copy', 
		invite_register_write:'Fill in when registering',
		invite_download_app:'download APP',
		invite_copy_success:'Copy successfully',

		
		invite_peoples:'Number of invitations',
		invite_time:'choose time', 
		invite_searchid:'search ID', 
		invite_bindnums:'number of connection',
		invite_lasttime:'Last active time',
		invite_earn_money:'Hurry up and invite friends to earn money',
		invite_starttime:'start time',
		invite_endtime:'end time', 
		invite_reset:'reset condition',
		invite_sure:'confirm',
		invite_date:'date',


		invite_income_detail:'Income Details',
		invite_friendid:'Friend ID',
		invite_chargetype:'Recharge Type',
		invite_paytype:'Payment Types',
		invite_income_num:'Recharge amount',
		invite_charge_amount:'Net recharge amount',
		invite_get_rate:'Commission ratio',
		invite_percent_reward:'Commission reward (invitation coin)',
		invite_charge_time:'Recharge time',


		invite_allget_detail:"Inviter's income details",
		invite_income_bills:'Profit Details',
		invite_charge_percent:'Recharge commission',
		invite_from:'From',
		invite_no_record:'No relevant records have been found',
		invite_reback_gold:'Gold coin recharge and return reward',
		invite_vip_reward:'VIP upgrade return reward',
		invite_svip_reward:'SVIP upgrade return reward',



		invite_friend_reward:'Invite friends to return rewards',
		invite_balance:'Reward balance',
		invite_normal_account:'The invitation account is normal! ',
		invite_error_account:'The invitation account has been frozen and no withdrawal is allowed! ',
		invite_get:'Receive',
		invite_total_reward:'Cumulative reward',
		invite_total_nums:'Cumulative number of invitations',
		invite_reward:'Invitation reward',
		invite_charge_reward:'Gold coin recharge reward',
		invite_percent4:'4% divided',
		invite_intro:'Description',
		invite_now_gold:'Invite friends to recharge, you will immediately get invitation coins;',
		invite_gold_money:'The number of invitation coins = the recharge amount of friends',
		invite_income_preview:'Profit preview',
		invite_case_one:'Case 1: You invite a friend to recharge 10,000 US dollars, you will immediately get the number of invitation coins =',
		invite_get_gold400:'You have 400 invitation coins',
		invite_grade_reward:'Member upgrade Award:',


		invite_percent8:'8% share',
		invite_grade_nowget:'Invite friends to upgrade membership, you will immediately get invitation coins;',
		invite_nums_grade:'The number of invitation coins = the amount of friends to upgrade their membership',
		invite_case_two:'Case 1: If you invite a friend to upgrade membership, it costs 9.99 USD, you will immediately get the number of invitation coins=',
		invite_gold_x:'You have X invitation coins. ',
		invite_rules:'Invitation rules',
		invite_rules_con1:'1. All users can participate in the invitation plan;',
		invite_rules_con2:'2. You send your own invitation code or share the invitation link to your friends; when you are invited to register, fill in the invitation code to bind to your name;',
		invite_rules_con3:'3. Invite friends to recharge, you can get 4% of invitation coins; friends upgrade membership, you can get 8% of invitation coins;',
		invite_rules_con4:'4. If your friends use Apple and Google Pay, because Apple Store and Google Store will charge a 30% handling fee, the share will be calculated based on the actual net amount received;',
		invite_rules_con5:'5. The share of invitation coins will be credited to the account in real time;',
		invite_rules_con6:'6. If you have any questions, please contact customer service',
		invite_go:'Go to invite',
		invite_copy_href:'The invitation link is copied successfully, send it to a friend to bind the invitation to earn money',
		invite_more100:'Only when the balance of invitation coins reaches 100 can you apply for the income',
		invite_fun_now:'This feature will be launched soon'
	}
}


