var adminLang = '';
var lang = 'zh';

if(localStorage.getItem('adminlg')){
	lang = localStorage.getItem('adminlg');
}
if(lang == 'zh') {
	adminLang = {
		langName: "中文简体",
		Promoterinfo: '请在客户端登录完善推广员信息！',
		indexTitle: '一对多聊天系统登录',
		loginon: '登录',
		popnumber:'请输入手机号',
		popass:'请输入密码',
		phoneerror: "手机号不能为空，请输入正确的手机号",
		phoneerror1: "手机号不正确，请输入正确的手机号",
		passworderror: "密码不能为空，请输入正确的手机号",
		PrivateMessaging: "私信群发",
		AllActivity: "全部动态",
		recentContact: '最近联系人',
		InfoNick: '昵称',
		Welcome: '欢迎你',
		Infofans: '粉丝',
		Infofollows: '关注',
		Infosign: '签名',
		yesfollows: '已关注',
		privateMessage: '私 信',
		dytitle: '发布动态',
		dyplaceholder: '请输入消息...',
		Publish: '发 布',
		dynamicTitle: '动态',
		chattxt: '说点儿什么吧？',
		dynamicno: '暂时没有动态',
		lookTranslation: '查看翻译',
		langSetting: '语言设置',
		dyfont1: '请输入评论',
		dyfont2: '评论',
		dyfont3: '取消',
		dyfont4: '不能为空',
		dyfont5: '评论成功',
		dyfont6: '取消评论',
		dyfont7: '请输入回复',
		dyfont8: '回复',
		dyfont9: '回复成功',
		dyfont10: '取消回复',
		dyfont11: '发布成功',
		notYet: '暂无动态',
		focussuccess:'关注成功',
		tips: '温馨提示',
		followtxt: '是否确认取消关注？',
		followdel: '取消关注成功',
		liveTitle: '交友列表',
		Previous: '上一页',
		NextPage: '下一页',
		videochat: '请在其他设备上接听！',
		sendcar: '赠送座驾',
		chatno: '其他',
		label1: '请选择',
		label2: '男',
		label3: '女',
		sendtitle: "已发送完毕！",
		lettern: "请选择要发送的用户",
		letterContry: '国家',
		letterGender: '性别',
		letterinfo:  '用户',
		letterSelect: '搜索',
		lSelect1: '已选中',
		lSelect2: '人',
		lSelect3: "预计发送时间",
		lSTime:'秒',
		selectAll: '全选',
		LSSending: '正在发送中',

	};
} else {
	adminLang = {
		langName: "English",
		Promoterinfo: 'Please log in the client to improve the information of the promoter！',
		indexTitle: 'Log in to one-to-many chat system',
		loginon: 'Login',
		popnumber:'Please enter your mobile phone number',
		popass:'Please enter your password',
		phoneerror: "Mobile phone number cannot be empty, please enter the correct phone number",
		phoneerror1: "The phone number is incorrect. Please enter the correct phone number",
		passworderror: "The password cannot be empty, please enter the correct mobile phone number",
		PrivateMessaging: "Send Private Messages",
		AllActivity: "Moments",
		recentContact: 'Contact',
		InfoNick: 'Nickname',
		Welcome: 'Welcome you',
		Infofans: 'Fans',
		Infofollows: 'Follow',
		Infosign: 'Mood signature',
		yesfollows: 'Following',
		privateMessage: 'Private Message',
		dytitle: 'Post moments',
		dyplaceholder: 'Please enter a message',
		Publish: 'Post',
		dynamicTitle: 'Moments',
		chattxt: 'Say something?',
		dynamicno: 'No new posts yet',
		lookTranslation: 'See translation',
		langSetting: 'Language setting',
		dyfont1: 'Please enter a comment',
		dyfont2: 'Comments',
		dyfont3: 'Cancel',
		dyfont4: 'Comment cannot be empty',
		dyfont5: 'Comment succeeded',
		dyfont6: 'Uncomment',
		dyfont7: 'Please enter a reply',
		dyfont8: 'Reply',
		dyfont9: 'Successful reply',
		dyfont10: 'Cancel reply',
		dyfont11: 'Published successfully',
		notYet: '~No data~',
		focussuccess:'Attention success',
		tips: 'Note',
		followtxt: 'Are you sure to unfollow?',
		followdel: 'Unfollow success',
		liveTitle: 'Dating List',
		Previous: 'Previous',
		NextPage: 'Next Page',
		videochat: 'Please answer on another device! ',
		sendcar: 'Giveaway car',
		chatno: 'Other',
		label1: 'Please select',
		label2: 'Male',
		label3: 'Female',
		sendtitle: "Sent!",
		lettern: "Please select a user to send",
		letterContry: 'Country',
		letterGender: 'Gender',
		letterinfo: 'User',
		letterSelect: 'Search',
		lSelect1: 'Selected',
		lSelect2: 'person',
		lSelect3: "Estimated send time",
		lSTime: 'second',
		selectAll: 'Select All',
		LSSending: 'Sending',
	};
}
